
pointer-function: pointer-function.c
	gcc pointer-function.c -o ./bin/pointer-function

pointer-array: pointer-array.c
	gcc pointer-array.c -o ./bin/pointer-array

pointers: pointers.c
	gcc pointers.c -o ./bin/pointers
array_func_pointers: array_func_pointers.c
	gcc array_func_pointers.c -o ./bin/array_func_pointers